# Generated by Django 5.2.7 on 2025-10-13 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numer_telefonu', models.CharField(blank=True, max_length=15)),
                ('data_rejestracji', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Owoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('cena_za_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kraj_pochodzenia', models.CharField(max_length=50)),
                ('dostepna_ilosc', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
