# Generated by Django 5.2.7 on 2025-10-20 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.FloatField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.klient')),
                ('owoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.owoc')),
            ],
        ),
    ]
