# Generated by Django 5.2.7 on 2025-11-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_zamowienia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienia',
            name='ilosc',
            field=models.IntegerField(),
        ),
    ]
